Vagrant.configure("2") do |config|
  # Указываем образ Ubuntu
  # config.vm.box = "ubuntu-jammy64"
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Пробрасываем порты
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Nginx
  config.vm.network "forwarded_port", guest: 8443, host: 8443 # Nginx
  config.vm.network "forwarded_port", guest: 8000, host: 8000 # django
  
  config.vm.hostname = "backend-vm"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "backend-vm"
    vb.memory = 4096
    vb.cpus = 4
    vb.gui = false
    vb.check_guest_additions=false
  end

  # Устанавливаем Docker через provision
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get upgrade -y
    sudo apt-get install -y ca-certificates curl
    sudo install -y -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update -y
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    sudo openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/private/nginx.crt -days 365 -subj "/C=BY"

    # Сборка и запуск контейнеров
    #cd /vagrant
    #docker-compose build
    #docker-compose up -d
  SHELL
end
  